Ip-Adress:
  192.168.4.214
Devices: 
  - "SM-6"
  - "SM-5"
  - "SM-4"
  - "SM-3"
  - "SM-2"
  - "SM-1"
Group-add: 
  "1.1.4":
    "3/0/0": "SM-6"
    "3/0/1": "SM-6"
    "3/0/2": "SM-6"
    "3/0/3": "SM-6"
  "1.1.5"
  "1.1.6"
  "1.1.7"
  "1.1.8"
  "1.1.9"
  "1.1.10"
  "1.1.11"
  "1.1.17"
KNX-Network:
  - "1.1.4":
    - "3/0/0": "SM-6"
    - "3/0/1": "SM-6"
    - "3/0/2": "SM-6"
    - "3/0/3": "SM-6"
  - "1.1.5":
  - "1.1.6"
  - "1.1.7"
  - "1.1.8"
  - "1.1.9"
  - "1.1.10"
  - "1.1.11"
  - "1.1.17"